skip_vim_plugin "haml"
skip_vim_plugin "jslint"
skip_vim_plugin "taglist"
skip_vim_plugin "align"
skip_vim_plugin "searchfold"
skip_vim_plugin "zoomwin"
vim_plugin_task "zencoding", "git://github.com/mattn/zencoding-vim.git"
vim_plugin_task "arpeggio", "git://github.com/kana/vim-arpeggio.git"
vim_plugin_task "lusty_explorer", "git://github.com/vim-scripts/LustyExplorer.git"
vim_plugin_task "hammer", "git://github.com/robgleeson/hammer.vim.git"
vim_plugin_task "vim-orgmode", "git://github.com/jceb/vim-orgmode.git"
vim_plugin_task "fuzzyfinder", "git://github.com/vim-scripts/FuzzyFinder.git"
vim_plugin_task "l9", "git://github.com/vim-scripts/L9.git"
vim_plugin_task "gundo", "git://github.com/sjl/gundo.vim.git"
